[package]
authors = ["Juliette Cordor", "Patrick Auernig <dev.patrick.auernig@gmail.com>"]
name = "discord-presence"
description = "A Rust client for Discord RPC."
keywords = ["discord", "rpc", "ipc"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/jewlexx/discord-presence.git"
version = "0.5.5"
edition = "2021"

[dependencies]
serde_json = "1.0"
byteorder = "1.4"
log = "0.4"
bytes = "1.1"
parking_lot = "0.12"
crossbeam-channel = "0.5"
num-derive = "0.3"
num-traits = "0.2"
thiserror = "1.0"
cfg-if = "1.0"

[target.'cfg(windows)'.dependencies]
named_pipe = "0.4"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.uuid]
version = "1.1"
features = ["v4"]

[dev-dependencies]
version-sync = "0.9"
